### ISSUE TITLE
GuliKit Hall Joystick 

### ISSUE THREAD

**Issue by suwagawaki** [tewtham/dactyl-typesafe#9]
Thanks for sharing the design! Will a [GuliKit hall effect joycon joystick](https://www.gulikit.com/productinfo/945307.html) work as an alternative to the dualshock analog stick?

**Comment by tewtham** [comment]
Yes, I think it can work, but you would need to fabricate a small riser for it to sit on since it is a bit shorter than the dualshock. My only concern would be that the opening is slightly wider (2-3mm) and more curved than the one on the switch. Could try just printing out the [left thumb switch](https://github.com/tewtham/dactyl-typesafe/blob/main/things/4x6-wireless/left-thumb-switches.stl) piece to see how well it fits. I might try it myself if I come across a broken switch controller!

**Comment by suwagawaki** [comment]
That makes sense, thanks for answering!
